# Generated by Django 5.2.5 on 2025-10-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='custom_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, choices=[('FOOD', 'FOOD'), ('Utilities', 'Utilities'), ('Healthcare', 'Healthcare'), ('Transport', 'Transport'), ('Rent', 'Rent'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
